INSERT INTO products ( product_name, shoe_size, description, Brand, price, category, imageURL, stock_quantity, gender )
            VALUES
            (
                        'Nike React Infinity Run Flyknit',
                        '40.5',
                        'ABC',
                        'NIKE',
                        160,
                        'RUNNING',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zX42Nc.jpg',
                        3,
                        'MEN'
            )
            ,
            (
                        'Nike React Miler',
                        '39.5',
                        'ABC',
                        'NIKE',
                        130,
                        'RUNNING',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5cc7de3b-2afc-49c2-a1e4-0508997d09e6/react-miler-mens-running-shoe-DgF6nr.jpg',
                        3,
                        'MEN'
            )
            ,
            (
                        'Nike Air Zoom Pegasus 37',
                        '37',
                        'ABC',
                        'NIKE',
                        120,
                        'RUNNING',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-33b0a0a5-c171-46cc-ad20-04a768703e47/air-zoom-pegasus-37-womens-running-shoe-Jl0bDf.jpg',
                        3,
                        'WOMEN'
            )
            ,
            (
                        'Nike Joyride Run Flyknit',
                        '36.5',
                        'ABC',
                        'NIKE',
                        180,
                        'RUNNING',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/99a7d3cb-e40c-4474-91c2-0f2e6d231fd2/joyride-run-flyknit-womens-running-shoe-HcfnJd.jpg',
                        3,
                        'WOMEN'
            )
            ,
            (
                        'Nike Mercurial Vapor 13 Elite FG',
                        '35',
                        'ABC',
                        'NIKE',
                        250,
                        'FOOTBALL',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9dda6202-e2ff-4711-9a09-0fcb7d90c164/mercurial-vapor-13-elite-fg-firm-ground-soccer-cleat-14MsF2.jpg',
                        3,
                        'WOMEN'
            )
            ,
            (
                        'Nike Phantom Vision Elite Dynamic Fit FG',
                        '37',
                        'ABC',
                        'NIKE',
                        150,
                        'FOOTBALL',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/s1amp7uosrn0nqpsxeue/phantom-vision-elite-dynamic-fit-fg-firm-ground-soccer-cleat-19Kv1V.jpg',
                        3,
                        'WOMEN'
            )
            ,
            (
                        'Nike Phantom Venom Academy FG',
                        '37.5',
                        'ABC',
                        'NIKE',
                        80,
                        'FOOTBALL',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/whegph8z9ornhxklc8rp/phantom-venom-academy-fg-firm-ground-soccer-cleat-6JVNll.jpg',
                        3,
                        'WOMEN'
            )
            ,
            (
                        'Nike Mercurial Vapor 13 Elite Tech Craft FG',
                        '44',
                        'ABC',
                        'NIKE',
                        145,
                        'FOOTBALL',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/vhbwnkor8sxt8qtecgia/mercurial-vapor-13-elite-tech-craft-fg-firm-ground-soccer-cleat-l38JPj.jpg',
                        3,
                        'MEN'
            )
            ,
            (
                        'Nike Mercurial Superfly 7 Pro MDS FG',
                        '42',
                        'ABC',
                        'NIKE',
                        137,
                        'FOOTBALL',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-a52a8aec-22dc-4982-961b-75c5f4c72805/mercurial-superfly-7-pro-mds-fg-firm-ground-soccer-cleat-mhcpdN.jpg',
                        3,
                        'MEN'
            )
            ,
            (
                        'Nike Air Force 1',
                        '30',
                        'ABC',
                        'NIKE',
                        90,
                        'CASUAL',
                        'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/178b2a46-3ee4-492b-882e-f71efdd53a36/air-force-1-big-kids-shoe-2zqp8D.jpg',
                        3,
                        'KIDS'
            )
            ,
            (
                        'Nike Renew Run',
                        '32',
                        'ABC',
                        'NIKE',
                        80,
                        'RUNNING',
                        'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-73e54c0b-11a6-478b-9f90-bd97fcde872d/renew-run-big-kids-running-shoe-5Bpz93.jpg',
                        3,
                        'KIDS'
            )
            ,
            (
                        'Bridgeport Advice',
                        '43',
                        'ABC',
                        'HUSHPUPPIES',
                        30,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/BRIDGPORT_ADVICE-BLACK_1_800x800.jpg?v=1576567903',
                        4,
                        'MEN'
            )
            ,
            (
                        'Beck',
                        '43',
                        'ABC',
                        'HUSHPUPPIES',
                        80,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/Beck-Black_800x800.jpg',
                        5,
                        'MEN'
            )
            ,
            (
                        'Fester',
                        '46',
                        'ABC',
                        'HUSHPUPPIES',
                        70,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/fester-Tan_800x800.jpg?v=1575537531',
                        6,
                        'MEN'
            )
            ,
            (
                        'Pixel',
                        '41',
                        'ABC',
                        'HUSHPUPPIES',
                        75,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/PIXEL-TAN_800x800.jpg?v=1577420506',
                        7,
                        'MEN'
            )
            ,
            (
                        'Austin',
                         '45',
                        'ABC',
                        'HUSHPUPPIES',
                        75,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/Austin-Coffee_800x800.jpg?v=1574772988',
                        2,
                        'MEN'
            )
            ,
            (
                        'SS-HL-0135',
                        '36.5',
                        'ABC',
                        'HUSHPUPPIES',
                        30,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009240000-11-SS-HL-0135-Black_800x800.jpg?v=1572264270',
                        6,
                        'WOMEN'
            )
            ,
            (
                        'SS-HL-0136',
                        '39',
                        'ABC',
                        'HUSHPUPPIES',
                        50,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009250000-779-SS-HL-0136-Coffee_800x800.jpg?v=1571900372',
                        4,
                        'WOMEN'
            )
            ,
            (
                        'SS-HL-0128',
                         '39',
                        'ABC',
                        'HUSHPUPPIES',
                        35,
                        'FORMAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/000300242-484-SS-HL-0128-Blue_800x800.jpg?v=1583235174',
                        3,
                        'WOMEN'
            )
            ,
            (
                        'SS-MS-0075',
                        '36',
                        'ABC',
                        'HUSHPUPPIES',
                        25,
                        'CASUAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009170000-479-SS-MS-0075-Red_800x800.jpg?v=1570688687',
                        7,
                        'WOMEN'
            )
            ,
            (
                        'SS-PM-0093',
                         '40',
                        'ABC',
                        'HUSHPUPPIES',
                        30,
                        'CASUAL',
                        'https://cdn.shopify.com/s/files/1/0016/0074/9623/products/SS-PM-0093_1_800x800.jpg?v=1570601253',
                        3,
                        'WOMEN'
            )
            ,
            (
                        'Nizza X Disney',
                         '31',
                        'ABC',
                        'ADIDAS',
                        55,
                        'CASUAL',
                        'https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/ef901c7aeac042578eceab9d0159196c_9366/Nizza_x_Disney_Sport_Goofy_Shoes_White_FW0651_01_standard.jpg',
                        6,
                        'KIDS'
            )
            ,
            (
                        'X_PLR',
                        '33',
                        'ABC',
                        'ADIDAS',
                        65,
                        'CASUAL',
                        'https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/a36518227134495da766ab9d01772fa2_9366/X_PLR_Shoes_Red_FY9063_01_standard.jpg',
                        5,
                        'KIDS'
            )
            ,
            (
                        'Stan Smith',
                      '34',
                        'ABC',
                        'ADIDAS',
                        55,
                        'CASUAL',
                        'https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/d0720712d81e42b1b30fa80800826447_9366/Stan_Smith_Shoes_White_M20607_M20607_01_standard.jpg',
                        3,
                        'KIDS'
            )
            ,
            (
                        'NMD_R1',
                       '31.5',
                        'ABC',
                        'ADIDAS',
                        120,
                        'RUNNING',
                        'https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/99ca762cb9054caf82fbabc500fd146e_9366/NMD_R1_Shoes_Blue_FY9392_01_standard.jpg',
                        3,
                        'KIDS'
            )
            ,
            (
                        'NMD_R1 Flash Red',
                         '36.5',
                        'ABC',
                        'ADIDAS',
                        140,
                        'CASUAL',
                        'https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/90f85768e3894aeaab67aba0014a3379_9366/NMD_R1_Shoes_Red_FY9389_01_standard.jpg',
                        5,
                        'WOMEN'
            )
            